name: Marketplace Recent Bot
on:
  issues:
    types: [opened]

jobs:
  add_to_recent:
    if: contains(github.event.issue.title, '[ADD_ME]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add to Recent List
        run: |
          URL=$(echo "${{ github.event.issue.body }}" | grep "SERVER_URL:" | cut -d ' ' -f 2)
          NAME=$(echo "${{ github.event.issue.title }}" | cut -d ' ' -f 2)
          # Specifically adding to RECENT list
          echo "$NAME:$URL" >> RECENT_PROVIDERS.TXT
          
      - name: Sync to GitHub
        run: |
          git config --global user.name "Terracina-Bot"
          git config --global user.email "bot@terracina-os.com"
          git add RECENT_PROVIDERS.TXT
          git commit -m "New Community Dev: ${{ github.event.issue.title }}"
          git push
          
